version: "3.5"

services:
  redis:
    image: 'dockerhub.ir/redis:6.2.3-alpine'
    container_name: redis

  rabbit:
    image: 'dockerhub.ir/rabbitmq:3.8.16-management-alpine'
    container_name: rabbit
    ports:
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root

networks:
  default:
    external:
      name: php-threading